Drink and Ingredient Models created
logan-nielsen/Frappuccino-Paradise-Group-3 pull request #72
Opened 2022-10-09 18:48 UTC by recneps121

2022-10-10 03:47 UTC, logan-nielsen commented
Looks good! I just have two minor comments before we merge this.
1. When I run the Django server I'm getting an error that says "No module named djmoney". Are you using the [django money](https://pypi.org/project/django-money/) package in your changes? If so I would add that to the requirements.txt file in the app/ directory with the version number you are using. The version can be easily found using the pip show command
2. Assuming I'm understanding correctly I don't think we need the canMake field in the Drink class. I think we can just compute this dynamically when it is needed based on the inventory and the store's current money rather than updating a database field every time an order is made. If you have a reason for doing this just let us know, these are just my thoughts.

2022-10-10 03:51 UTC, logan-nielsen requested changes
Looks good! I just have two minor comments before we merge this.
1. When I run the Django server I'm getting an error that says "No module named djmoney". Are you using the [django money](https://pypi.org/project/django-money/) package in your changes? If so I would add that to the requirements.txt file in the app/ directory with the version number you are using. The version can be easily found using the pip show command
2. Assuming I'm understanding correctly I don't think we need the canMake field in the Drink class. I think we can just compute this dynamically when it is needed based on the inventory and the store's current money rather than updating a database field every time an order is made. If you have a reason for doing this just let us know, these are just my thoughts.

2022-10-12 00:43 UTC, recneps121 commented
Alright I removed the can_make field from Drink and added django-money to the requirements file. Let me know if there's anything else you can think of.

2022-10-12 17:35 UTC, logan-nielsen approved these changes

2022-10-12 17:36 UTC, merged